site_name: Docker4PHP Documentation

repo_url: https://github.com/wodby/docker4php
site_description: 'Docker4PHP – Docker-based PHP environment for local development'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Getting Started: 'index.md'
  - Domains: 'domains.md'
  - Logs: 'logs.md'
  - Accessing Containers: 'access.md'
  - Permissions: 'permissions.md'
  - Docker for Mac: 'macos.md'
  - Multiple Projects: 'multiple-projects.md'
  - Containers:
    - 'Nginx': 'containers/nginx.md'
    - 'Apache': 'containers/apache.md'
    - 'PHP': 'containers/php.md'
    - 'MariaDB': 'containers/mariadb.md'
    - 'PostgreSQL': 'containers/postgres.md'
    - 'Redis': 'containers/redis.md'
    - 'Memcached': 'containers/memcached.md'
    - 'Apache Solr': 'containers/solr.md'
    - 'Varnish': 'containers/varnish.md'
    - 'AthenaPDF': 'containers/athenapdf.md'
    - 'Rsyslog': 'containers/rsyslog.md'
    - 'Webgrind': 'containers/webgrind.md'
    - 'Blackfire': 'containers/blackfire.md'
